[project]
name = ""
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certifi>=2025.8.3",
    "fire>=0.7.1",
    "ipykernel>=6.30.1",
    "ipython>=9.5.0",
    "mlflow>=3.3.2",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]